name: wallet_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets\Group 10.png
  - assets\Amazon.png
  - assets\Facebook_f_logo_(2019) 1.png
  - assets\Frame 4.png
  - assets\g1520.png
  - assets\Group 9.png
  - assets\Icon (2).png
  - assets\Icon (3).png
  - assets\Icon (4).png
  - assets\Icon (5).png
  - assets\Icon (6).png
  - assets\Icon (7).png
  - assets\Icon (8).png
  - assets\Icon (9).png
  - assets\Icon (10).png
  - assets\Icon (11).png
  - assets\Icon.png
  - assets\image 8.png
  - assets\Jordan (JO).png
  - assets\Netflix.png
  - assets\Profile photo (3).png
  - assets\Profile photo.png
  - assets\The home depot.png
  - assets\Topup.png
  - assets\Group 4.png
  - assets\Group 4 (2).png
  - assets\Topup.png
  - assets\upload-line.png
  - assets\Vector (12).png
  - assets\wallet-fill.png
  - assets\wallet-line.png
  - assets\The home depot.png
  - assets\home-3-fill.png
  - assets\home-3-line.png
  - assets\bank-card-2-fill.png
  - assets\bank-card-2-line.png
  - assets\download-line.png
  - assets\Wallmart.png
  - assets\file-list-3-fill.png
  - assets\file-list-3-line.png
  


