// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdBvcVK9tLF2srWLDTo7YiHzM8jGMRjqk',
    appId: '1:162158255750:web:2a30925c0480bc7a9b7b07',
    messagingSenderId: '162158255750',
    projectId: 'student-app-f7a7b',
    authDomain: 'student-app-f7a7b.firebaseapp.com',
    storageBucket: 'student-app-f7a7b.appspot.com',
    measurementId: 'G-5SH5XZ64WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYmMZ2rPtpzBEwEGlrvE32T7JMBXMhsD0',
    appId: '1:162158255750:android:90fb4ecc7e7d76be9b7b07',
    messagingSenderId: '162158255750',
    projectId: 'student-app-f7a7b',
    storageBucket: 'student-app-f7a7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnUMy7HZQXBpxjYeTj7f6cLQovMMB69GU',
    appId: '1:162158255750:ios:9b3e2c954242d0b29b7b07',
    messagingSenderId: '162158255750',
    projectId: 'student-app-f7a7b',
    storageBucket: 'student-app-f7a7b.appspot.com',
    iosBundleId: 'com.example.studentAnnouncement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnUMy7HZQXBpxjYeTj7f6cLQovMMB69GU',
    appId: '1:162158255750:ios:9b3e2c954242d0b29b7b07',
    messagingSenderId: '162158255750',
    projectId: 'student-app-f7a7b',
    storageBucket: 'student-app-f7a7b.appspot.com',
    iosBundleId: 'com.example.studentAnnouncement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdBvcVK9tLF2srWLDTo7YiHzM8jGMRjqk',
    appId: '1:162158255750:web:fbe3f96f34317bef9b7b07',
    messagingSenderId: '162158255750',
    projectId: 'student-app-f7a7b',
    authDomain: 'student-app-f7a7b.firebaseapp.com',
    storageBucket: 'student-app-f7a7b.appspot.com',
    measurementId: 'G-KWEPVCXH9X',
  );
}
