name: plants_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  firebase_storage: ^11.6.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets\plantimg1.png
  - assets\plant img2.png
  - assets\Group 5314.png
  - assets\shopping-bag.png
  - assets\Group 5318.png
  - assets\thermometer.png
  - assets\Vector (11).png
  - assets\Group 5470.png
 
