name: bicycle_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets\image 3.png
  - assets\image 6 (1).png
  - assets\image 6.png
  - assets\pngwing (1).png
  - assets\pngwing (3).png
  - assets\pngwing.png
  - assets\search-normal.png
  - assets\pngwing (4).png
  - assets\image 2.png
  - assets\image 1 (1).png
  - assets\image 3 (1).png
  - assets\image 4.png
  - assets\house.png
  - assets\vc.png
  - assets\user.png
  - assets\shop.png
