name: fashion_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets\Rectangle 980 (1).png
  - assets\Rectangle 980.png
  - assets\Rectangle 981 (1).png
  - assets\Rectangle 981 (2).png
  - assets\Rectangle 981.png
  - assets\Rectangle 984.png
  - assets\Rectangle 989.png
  - assets\Group 38.png
  - assets\Home.png
  - assets\Menu.png
  - assets\Profile.png
  - assets\Cart.png
