name: music_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  path: ^1.9.0
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  audio_video_progress_bar: ^2.0.3
  audioplayers: ^6.0.0
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2
  flutter_slidable: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets\44 1.png
  - assets\111 1.png
  - assets\272cf15a08dcca3bd22e258e7635e9c2 1.png
  - assets\Rectangle 32.png
  - assets\Rectangle 34.png
  - assets\Rectangle 38.png
  - assets\Rectangle 39.png
  - assets\Rectangle 40.png
  - assets/audio/
  - assets\Faded.png
  - assets\gulabi sadi.jpg
  - assets\jocker.jpg
  - assets\music1.jpg
  - assets\moneyh.jpg
  - assets\music4.jpeg
  - assets\nadaniya.jpg
  - assets\pirates.png
  - assets\suniyas.jpg
  - assets\yjhd.jpg
  - assets\imgprofile.png
  - assets\Icon (8).png
  - assets\Icon (9).png
  - assets\Icon (10).png
  - assets\Icon (11).png
  - assets\equalizer-line.png




