name: advance_quize_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets\Vector (1).png
  - assets\Vector (2).png
  - assets\Vector (3).png
  - assets\Vector (4).png
  - assets\Vector (5).png
  - assets\Vector (6).png
  - assets\Vector.png
  - assets\image 1.png
  - assets\Vector (8).png
  - assets\Logo.png
