// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnyV2TqqVuTjFV2D8m4EA-rQNE-NGu9to',
    appId: '1:740996173447:web:f42fb54dbedf674ed9b222',
    messagingSenderId: '740996173447',
    projectId: 'pet-care-app-4b032',
    authDomain: 'pet-care-app-4b032.firebaseapp.com',
    storageBucket: 'pet-care-app-4b032.appspot.com',
    measurementId: 'G-KZQJSQ5823',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALmiZyC13ilcli3_fNiV5j0MD5Ia5TWm4',
    appId: '1:740996173447:android:8c47596322cdb212d9b222',
    messagingSenderId: '740996173447',
    projectId: 'pet-care-app-4b032',
    storageBucket: 'pet-care-app-4b032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC75fxPJoOYveHBtvq6Yo5dAkvje-MSVcE',
    appId: '1:740996173447:ios:c150c78eb4f90571d9b222',
    messagingSenderId: '740996173447',
    projectId: 'pet-care-app-4b032',
    storageBucket: 'pet-care-app-4b032.appspot.com',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC75fxPJoOYveHBtvq6Yo5dAkvje-MSVcE',
    appId: '1:740996173447:ios:c150c78eb4f90571d9b222',
    messagingSenderId: '740996173447',
    projectId: 'pet-care-app-4b032',
    storageBucket: 'pet-care-app-4b032.appspot.com',
    iosBundleId: 'com.example.petCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnyV2TqqVuTjFV2D8m4EA-rQNE-NGu9to',
    appId: '1:740996173447:web:05046b4c4b5d9d01d9b222',
    messagingSenderId: '740996173447',
    projectId: 'pet-care-app-4b032',
    authDomain: 'pet-care-app-4b032.firebaseapp.com',
    storageBucket: 'pet-care-app-4b032.appspot.com',
    measurementId: 'G-GMGLK9HVS7',
  );
}
